import type { FoodItem } from "./types";

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: "round_popsicle",
    name: "Round popsicle",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "triangle_popsicle",
    name: "Triangle popsicle",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "jellybean_bear",
    name: "Jellybean bear",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "strawberry",
    name: "Strawberry",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  { id: "cheese", name: "Cheese", requiresCooking: false, cookTimeSeconds: 0 },
  {
    id: "lettuce",
    name: "Lettuce",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  { id: "tomato", name: "Tomato", requiresCooking: false, cookTimeSeconds: 0 },
  {
    id: "spiral_candy",
    name: "Spiral candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "round_candy",
    name: "Round candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "star_candy",
    name: "Star candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "heart_candy",
    name: "Heart candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "rectangular_candy",
    name: "Rectangular candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },
  {
    id: "flower_candy",
    name: "Flower candy",
    requiresCooking: false,
    cookTimeSeconds: 0,
  },

  {
    id: "bread_slices",
    name: "Bread slices",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "baguette",
    name: "Baguette",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "cinnamon_roll",
    name: "Cinnamon roll",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "small_loaf",
    name: "Small loaf",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "braided_bread_loaf",
    name: "Braided bread loaf",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "round_bun",
    name: "Round bun",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "pineapple_bun",
    name: "Pineapple bun",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "dumpling",
    name: "Dumpling",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "noodles",
    name: "Noodles",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "waffles",
    name: "Waffles",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  {
    id: "burger_bun",
    name: "Burger bun",
    requiresCooking: true,
    cookTimeSeconds: 30,
  },
  { id: "hotdog", name: "Hotdog", requiresCooking: true, cookTimeSeconds: 20 },
  { id: "bacon", name: "Bacon", requiresCooking: true, cookTimeSeconds: 20 },
  { id: "corn", name: "Corn", requiresCooking: true, cookTimeSeconds: 10 },
  {
    id: "capsicum",
    name: "Capsicum",
    requiresCooking: true,
    cookTimeSeconds: 10,
  },
  {
    id: "mushroom",
    name: "Mushroom",
    requiresCooking: true,
    cookTimeSeconds: 10,
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    requiresCooking: true,
    cookTimeSeconds: 10,
  },
  { id: "carrot", name: "Carrot", requiresCooking: true, cookTimeSeconds: 10 },
  { id: "fries", name: "Fries", requiresCooking: true, cookTimeSeconds: 10 },
];
