import type { OrderTemplate } from "./types";

export const HARD_ORDERS: OrderTemplate[] = [
  {
    orderNo: "6842",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 6 8 4 2. I want a burger at zone \"B\" with a brown top burger bun, yellow cheese, red tomato, light green lettuce, and a brown bottom burger bun. I also want a purple heart candy at zone \"D\".",
    items: [
      {
        zone: "B",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "brown",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "red",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "light green",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "burger_bun",
        colour: "brown",
      },
      { zone: "D", foodItemId: "heart_candy", colour: "purple" },
    ],
  },
  {
    orderNo: "3197",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 3 1 9 7. I want a breakfast plate at zone \"A\" with orange waffles, pink bacon, and yellow fries. I also want a blue round popsicle at zone \"C\".",
    items: [
      {
        zone: "A",
        parentItem: "breakfast_plate",
        sequence: 1,
        foodItemId: "waffles",
        colour: "orange",
      },
      {
        zone: "A",
        parentItem: "breakfast_plate",
        sequence: 2,
        foodItemId: "bacon",
        colour: "pink",
      },
      {
        zone: "A",
        parentItem: "breakfast_plate",
        sequence: 3,
        foodItemId: "fries",
        colour: "yellow",
      },
      { zone: "C", foodItemId: "round_popsicle", colour: "blue" },
    ],
  },
  {
    orderNo: "9074",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 9 0 7 4. I want a noodle bowl at zone \"C\" with dark green noodles, red mushroom, yellow corn, and purple carrot. I also want a pink star candy at zone \"A\".",
    items: [
      {
        zone: "C",
        parentItem: "noodle_bowl",
        sequence: 1,
        foodItemId: "noodles",
        colour: "dark green",
      },
      {
        zone: "C",
        parentItem: "noodle_bowl",
        sequence: 2,
        foodItemId: "mushroom",
        colour: "red",
      },
      {
        zone: "C",
        parentItem: "noodle_bowl",
        sequence: 3,
        foodItemId: "corn",
        colour: "yellow",
      },
      {
        zone: "C",
        parentItem: "noodle_bowl",
        sequence: 4,
        foodItemId: "carrot",
        colour: "purple",
      },
      { zone: "A", foodItemId: "star_candy", colour: "pink" },
    ],
  },
  {
    orderNo: "2461",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 2 4 6 1. I want a hotdog set at zone \"D\" with a brown round bun, orange hotdog, dark green lettuce, and red tomato. I also want blue fries at zone \"B\".",
    items: [
      {
        zone: "D",
        parentItem: "hotdog_set",
        sequence: 1,
        foodItemId: "round_bun",
        colour: "brown",
      },
      {
        zone: "D",
        parentItem: "hotdog_set",
        sequence: 2,
        foodItemId: "hotdog",
        colour: "orange",
      },
      {
        zone: "D",
        parentItem: "hotdog_set",
        sequence: 3,
        foodItemId: "lettuce",
        colour: "dark green",
      },
      {
        zone: "D",
        parentItem: "hotdog_set",
        sequence: 4,
        foodItemId: "tomato",
        colour: "red",
      },
      { zone: "B", foodItemId: "fries", colour: "blue" },
    ],
  },
  {
    orderNo: "7580",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 7 5 8 0. I want a bread basket at zone \"A\" with brown baguette, yellow bread slices, and orange braided bread loaf. Put purple flower candy at zone \"D\".",
    items: [
      {
        zone: "A",
        parentItem: "bread_basket",
        sequence: 1,
        foodItemId: "baguette",
        colour: "brown",
      },
      {
        zone: "A",
        parentItem: "bread_basket",
        sequence: 2,
        foodItemId: "bread_slices",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "bread_basket",
        sequence: 3,
        foodItemId: "braided_bread_loaf",
        colour: "orange",
      },
      { zone: "D", foodItemId: "flower_candy", colour: "purple" },
    ],
  },
  {
    orderNo: "5316",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 5 3 1 6. I want a veggie plate at zone \"B\" with light green capsicum, orange carrot, yellow corn, and blue cauliflower. I also want a red rectangular candy at zone \"C\".",
    items: [
      {
        zone: "B",
        parentItem: "veggie_plate",
        sequence: 1,
        foodItemId: "capsicum",
        colour: "light green",
      },
      {
        zone: "B",
        parentItem: "veggie_plate",
        sequence: 2,
        foodItemId: "carrot",
        colour: "orange",
      },
      {
        zone: "B",
        parentItem: "veggie_plate",
        sequence: 3,
        foodItemId: "corn",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "veggie_plate",
        sequence: 4,
        foodItemId: "cauliflower",
        colour: "blue",
      },
      { zone: "C", foodItemId: "rectangular_candy", colour: "red" },
    ],
  },
  {
    orderNo: "1908",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 1 9 0 8. I want a burger at zone \"A\" with a purple top burger bun, pink cheese, blue tomato, yellow lettuce, and a purple bottom burger bun. I also want dark green corn at zone \"C\".",
    items: [
      {
        zone: "A",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "purple",
      },
      {
        zone: "A",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "pink",
      },
      {
        zone: "A",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "blue",
      },
      {
        zone: "A",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "burger_bun",
        colour: "purple",
      },
      { zone: "C", foodItemId: "corn", colour: "dark green" },
    ],
  },
  {
    orderNo: "4725",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 4 7 2 5. I want a snack plate at zone \"D\" with red dumpling, yellow fries, and brown bacon. I also want light green round candy at zone \"A\" and pink strawberry at zone \"B\".",
    items: [
      {
        zone: "D",
        parentItem: "snack_plate",
        sequence: 1,
        foodItemId: "dumpling",
        colour: "red",
      },
      {
        zone: "D",
        parentItem: "snack_plate",
        sequence: 2,
        foodItemId: "fries",
        colour: "yellow",
      },
      {
        zone: "D",
        parentItem: "snack_plate",
        sequence: 3,
        foodItemId: "bacon",
        colour: "brown",
      },
      { zone: "A", foodItemId: "round_candy", colour: "light green" },
      { zone: "B", foodItemId: "strawberry", colour: "pink" },
    ],
  },
  {
    orderNo: "8653",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 8 6 5 3. I want a pastry plate at zone \"B\" with pink cinnamon roll, brown small loaf, and yellow pineapple bun. I also want blue heart candy at zone \"D\".",
    items: [
      {
        zone: "B",
        parentItem: "pastry_plate",
        sequence: 1,
        foodItemId: "cinnamon_roll",
        colour: "pink",
      },
      {
        zone: "B",
        parentItem: "pastry_plate",
        sequence: 2,
        foodItemId: "small_loaf",
        colour: "brown",
      },
      {
        zone: "B",
        parentItem: "pastry_plate",
        sequence: 3,
        foodItemId: "pineapple_bun",
        colour: "yellow",
      },
      { zone: "D", foodItemId: "heart_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "6049",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 6 0 4 9. I want noodles at zone \"C\" with orange noodles, dark green capsicum, blue mushroom, and red bacon. I also want purple triangle popsicle at zone \"A\".",
    items: [
      {
        zone: "C",
        parentItem: "noodle_plate",
        sequence: 1,
        foodItemId: "noodles",
        colour: "orange",
      },
      {
        zone: "C",
        parentItem: "noodle_plate",
        sequence: 2,
        foodItemId: "capsicum",
        colour: "dark green",
      },
      {
        zone: "C",
        parentItem: "noodle_plate",
        sequence: 3,
        foodItemId: "mushroom",
        colour: "blue",
      },
      {
        zone: "C",
        parentItem: "noodle_plate",
        sequence: 4,
        foodItemId: "bacon",
        colour: "red",
      },
      { zone: "A", foodItemId: "triangle_popsicle", colour: "purple" },
    ],
  },
  {
    orderNo: "3170",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 3 1 7 0. I want a four zone order. Zone \"A\" has blue waffles. Zone \"B\" has dark green cheese. Zone \"C\" has yellow carrot. Zone \"D\" has red star candy.",
    items: [
      { zone: "A", foodItemId: "waffles", colour: "blue" },
      { zone: "B", foodItemId: "cheese", colour: "dark green" },
      { zone: "C", foodItemId: "carrot", colour: "yellow" },
      { zone: "D", foodItemId: "star_candy", colour: "red" },
    ],
  },
  {
    orderNo: "9286",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 9 2 8 6. I want a sandwich at zone \"A\" with brown bread slices, yellow cheese, red tomato, light green lettuce, and brown bread slices. I also want pink round candy at zone \"D\".",
    items: [
      {
        zone: "A",
        parentItem: "sandwich",
        sequence: 1,
        foodItemId: "bread_slices",
        colour: "brown",
      },
      {
        zone: "A",
        parentItem: "sandwich",
        sequence: 2,
        foodItemId: "cheese",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "sandwich",
        sequence: 3,
        foodItemId: "tomato",
        colour: "red",
      },
      {
        zone: "A",
        parentItem: "sandwich",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "light green",
      },
      {
        zone: "A",
        parentItem: "sandwich",
        sequence: 5,
        foodItemId: "bread_slices",
        colour: "brown",
      },
      { zone: "D", foodItemId: "round_candy", colour: "pink" },
    ],
  },
  {
    orderNo: "4502",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 4 5 0 2. I want a burger at zone \"D\" with orange top burger bun, blue cheese, light green tomato, purple lettuce, pink bacon, and orange bottom burger bun.",
    items: [
      {
        zone: "D",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "orange",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "blue",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "light green",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "purple",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "bacon",
        colour: "pink",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 6,
        foodItemId: "burger_bun",
        colour: "orange",
      },
    ],
  },
  {
    orderNo: "7834",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 7 8 3 4. I want a cooked trio at zone \"B\" with purple dumpling, yellow hotdog, and light green fries. Put blue flower candy at zone \"C\" and red jellybean bear at zone \"A\".",
    items: [
      {
        zone: "B",
        parentItem: "cooked_trio",
        sequence: 1,
        foodItemId: "dumpling",
        colour: "purple",
      },
      {
        zone: "B",
        parentItem: "cooked_trio",
        sequence: 2,
        foodItemId: "hotdog",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "cooked_trio",
        sequence: 3,
        foodItemId: "fries",
        colour: "light green",
      },
      { zone: "C", foodItemId: "flower_candy", colour: "blue" },
      { zone: "A", foodItemId: "jellybean_bear", colour: "red" },
    ],
  },
  {
    orderNo: "1265",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 1 2 6 5. I want a veggie noodle plate at zone \"A\" with blue noodles, yellow cauliflower, light green capsicum, and orange mushroom. I also want purple rectangular candy at zone \"B\".",
    items: [
      {
        zone: "A",
        parentItem: "veggie_noodle_plate",
        sequence: 1,
        foodItemId: "noodles",
        colour: "blue",
      },
      {
        zone: "A",
        parentItem: "veggie_noodle_plate",
        sequence: 2,
        foodItemId: "cauliflower",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "veggie_noodle_plate",
        sequence: 3,
        foodItemId: "capsicum",
        colour: "light green",
      },
      {
        zone: "A",
        parentItem: "veggie_noodle_plate",
        sequence: 4,
        foodItemId: "mushroom",
        colour: "orange",
      },
      { zone: "B", foodItemId: "rectangular_candy", colour: "purple" },
    ],
  },
  {
    orderNo: "5907",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 5 9 0 7. I want dessert at zone \"C\" with pink waffles, brown cinnamon roll, and yellow pineapple bun. I also want light green round popsicle at zone \"D\".",
    items: [
      {
        zone: "C",
        parentItem: "dessert_plate",
        sequence: 1,
        foodItemId: "waffles",
        colour: "pink",
      },
      {
        zone: "C",
        parentItem: "dessert_plate",
        sequence: 2,
        foodItemId: "cinnamon_roll",
        colour: "brown",
      },
      {
        zone: "C",
        parentItem: "dessert_plate",
        sequence: 3,
        foodItemId: "pineapple_bun",
        colour: "yellow",
      },
      { zone: "D", foodItemId: "round_popsicle", colour: "light green" },
    ],
  },
  {
    orderNo: "8721",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 8 7 2 1. I want a hotdog plate at zone \"A\" with red hotdog, brown round bun, yellow fries, and light green lettuce. I also want blue heart candy at zone \"C\".",
    items: [
      {
        zone: "A",
        parentItem: "hotdog_plate",
        sequence: 1,
        foodItemId: "hotdog",
        colour: "red",
      },
      {
        zone: "A",
        parentItem: "hotdog_plate",
        sequence: 2,
        foodItemId: "round_bun",
        colour: "brown",
      },
      {
        zone: "A",
        parentItem: "hotdog_plate",
        sequence: 3,
        foodItemId: "fries",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "hotdog_plate",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "light green",
      },
      { zone: "C", foodItemId: "heart_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "3046",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 3 0 4 6. I want a mixed plate at zone \"D\" with purple bacon, orange carrot, blue corn, and yellow mushroom. Put red spiral candy at zone \"B\".",
    items: [
      {
        zone: "D",
        parentItem: "mixed_plate",
        sequence: 1,
        foodItemId: "bacon",
        colour: "purple",
      },
      {
        zone: "D",
        parentItem: "mixed_plate",
        sequence: 2,
        foodItemId: "carrot",
        colour: "orange",
      },
      {
        zone: "D",
        parentItem: "mixed_plate",
        sequence: 3,
        foodItemId: "corn",
        colour: "blue",
      },
      {
        zone: "D",
        parentItem: "mixed_plate",
        sequence: 4,
        foodItemId: "mushroom",
        colour: "yellow",
      },
      { zone: "B", foodItemId: "spiral_candy", colour: "red" },
    ],
  },
  {
    orderNo: "6418",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 6 4 1 8. I want a four zone order. Zone \"A\" has yellow baguette. Zone \"B\" has purple tomato. Zone \"C\" has light green fries. Zone \"D\" has pink flower candy.",
    items: [
      { zone: "A", foodItemId: "baguette", colour: "yellow" },
      { zone: "B", foodItemId: "tomato", colour: "purple" },
      { zone: "C", foodItemId: "fries", colour: "light green" },
      { zone: "D", foodItemId: "flower_candy", colour: "pink" },
    ],
  },
  {
    orderNo: "2593",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 2 5 9 3. I want a burger at zone \"C\" with blue top burger bun, red cheese, yellow tomato, light green lettuce, brown bacon, and blue bottom burger bun. Also put orange star candy at zone \"A\".",
    items: [
      {
        zone: "C",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "blue",
      },
      {
        zone: "C",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "red",
      },
      {
        zone: "C",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "yellow",
      },
      {
        zone: "C",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "light green",
      },
      {
        zone: "C",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "bacon",
        colour: "brown",
      },
      {
        zone: "C",
        parentItem: "burger",
        sequence: 6,
        foodItemId: "burger_bun",
        colour: "blue",
      },
      { zone: "A", foodItemId: "star_candy", colour: "orange" },
    ],
  },
  {
    orderNo: "7082",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 7 0 8 2. I want a bread and veggie plate at zone \"B\" with brown small loaf, light green cauliflower, yellow corn, and red capsicum. Put blue round candy at zone \"D\".",
    items: [
      {
        zone: "B",
        parentItem: "bread_and_veggie_plate",
        sequence: 1,
        foodItemId: "small_loaf",
        colour: "brown",
      },
      {
        zone: "B",
        parentItem: "bread_and_veggie_plate",
        sequence: 2,
        foodItemId: "cauliflower",
        colour: "light green",
      },
      {
        zone: "B",
        parentItem: "bread_and_veggie_plate",
        sequence: 3,
        foodItemId: "corn",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "bread_and_veggie_plate",
        sequence: 4,
        foodItemId: "capsicum",
        colour: "red",
      },
      { zone: "D", foodItemId: "round_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "4359",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 4 3 5 9. I want a breakfast set at zone \"A\" with yellow waffles, pink bacon, orange fries, and brown bread slices. I also want purple jellybean bear at zone \"C\".",
    items: [
      {
        zone: "A",
        parentItem: "breakfast_set",
        sequence: 1,
        foodItemId: "waffles",
        colour: "yellow",
      },
      {
        zone: "A",
        parentItem: "breakfast_set",
        sequence: 2,
        foodItemId: "bacon",
        colour: "pink",
      },
      {
        zone: "A",
        parentItem: "breakfast_set",
        sequence: 3,
        foodItemId: "fries",
        colour: "orange",
      },
      {
        zone: "A",
        parentItem: "breakfast_set",
        sequence: 4,
        foodItemId: "bread_slices",
        colour: "brown",
      },
      { zone: "C", foodItemId: "jellybean_bear", colour: "purple" },
    ],
  },
  {
    orderNo: "9164",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 9 1 6 4. I want a noodle bowl at zone \"D\" with red noodles, yellow dumpling, light green mushroom, and purple carrot. I also want blue rectangular candy at zone \"B\".",
    items: [
      {
        zone: "D",
        parentItem: "noodle_bowl",
        sequence: 1,
        foodItemId: "noodles",
        colour: "red",
      },
      {
        zone: "D",
        parentItem: "noodle_bowl",
        sequence: 2,
        foodItemId: "dumpling",
        colour: "yellow",
      },
      {
        zone: "D",
        parentItem: "noodle_bowl",
        sequence: 3,
        foodItemId: "mushroom",
        colour: "light green",
      },
      {
        zone: "D",
        parentItem: "noodle_bowl",
        sequence: 4,
        foodItemId: "carrot",
        colour: "purple",
      },
      { zone: "B", foodItemId: "rectangular_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "1206",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 1 2 0 6. I want a colour mix at zone \"C\" with pink round bun, dark green cheese, orange tomato, and blue lettuce. Put yellow heart candy at zone \"A\".",
    items: [
      {
        zone: "C",
        parentItem: "colour_mix",
        sequence: 1,
        foodItemId: "round_bun",
        colour: "pink",
      },
      {
        zone: "C",
        parentItem: "colour_mix",
        sequence: 2,
        foodItemId: "cheese",
        colour: "dark green",
      },
      {
        zone: "C",
        parentItem: "colour_mix",
        sequence: 3,
        foodItemId: "tomato",
        colour: "orange",
      },
      {
        zone: "C",
        parentItem: "colour_mix",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "blue",
      },
      { zone: "A", foodItemId: "heart_candy", colour: "yellow" },
    ],
  },
  {
    orderNo: "6975",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 6 9 7 5. I want a party plate at zone \"B\" with purple hotdog, yellow fries, dark green corn, and red cauliflower. I also want orange triangle popsicle at zone \"D\".",
    items: [
      {
        zone: "B",
        parentItem: "party_plate",
        sequence: 1,
        foodItemId: "hotdog",
        colour: "purple",
      },
      {
        zone: "B",
        parentItem: "party_plate",
        sequence: 2,
        foodItemId: "fries",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "party_plate",
        sequence: 3,
        foodItemId: "corn",
        colour: "dark green",
      },
      {
        zone: "B",
        parentItem: "party_plate",
        sequence: 4,
        foodItemId: "cauliflower",
        colour: "red",
      },
      { zone: "D", foodItemId: "triangle_popsicle", colour: "orange" },
    ],
  },
  {
    orderNo: "3814",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 3 8 1 4. I want a pastry stack at zone \"A\" with brown cinnamon roll, pink pineapple bun, and yellow braided bread loaf. Put dark green spiral candy at zone \"C\" and blue strawberry at zone \"D\".",
    items: [
      {
        zone: "A",
        parentItem: "pastry_stack",
        sequence: 1,
        foodItemId: "cinnamon_roll",
        colour: "brown",
      },
      {
        zone: "A",
        parentItem: "pastry_stack",
        sequence: 2,
        foodItemId: "pineapple_bun",
        colour: "pink",
      },
      {
        zone: "A",
        parentItem: "pastry_stack",
        sequence: 3,
        foodItemId: "braided_bread_loaf",
        colour: "yellow",
      },
      { zone: "C", foodItemId: "spiral_candy", colour: "dark green" },
      { zone: "D", foodItemId: "strawberry", colour: "blue" },
    ],
  },
  {
    orderNo: "8509",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 8 5 0 9. I want a burger at zone \"D\" with dark green top burger bun, orange cheese, pink tomato, purple lettuce, yellow bacon, and dark green bottom burger bun.",
    items: [
      {
        zone: "D",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "dark green",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "orange",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "pink",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "purple",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "bacon",
        colour: "yellow",
      },
      {
        zone: "D",
        parentItem: "burger",
        sequence: 6,
        foodItemId: "burger_bun",
        colour: "dark green",
      },
    ],
  },
  {
    orderNo: "2730",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 2 7 3 0. I want a four zone order. Zone \"A\" has purple dumpling. Zone \"B\" has yellow star candy. Zone \"C\" has brown baguette. Zone \"D\" has red mushroom.",
    items: [
      { zone: "A", foodItemId: "dumpling", colour: "purple" },
      { zone: "B", foodItemId: "star_candy", colour: "yellow" },
      { zone: "C", foodItemId: "baguette", colour: "brown" },
      { zone: "D", foodItemId: "mushroom", colour: "red" },
    ],
  },
  {
    orderNo: "5698",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 5 6 9 8. I want a sandwich at zone \"C\" with blue bread slices, pink cheese, red tomato, yellow lettuce, and blue bread slices. I also want light green fries at zone \"A\".",
    items: [
      {
        zone: "C",
        parentItem: "sandwich",
        sequence: 1,
        foodItemId: "bread_slices",
        colour: "blue",
      },
      {
        zone: "C",
        parentItem: "sandwich",
        sequence: 2,
        foodItemId: "cheese",
        colour: "pink",
      },
      {
        zone: "C",
        parentItem: "sandwich",
        sequence: 3,
        foodItemId: "tomato",
        colour: "red",
      },
      {
        zone: "C",
        parentItem: "sandwich",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "yellow",
      },
      {
        zone: "C",
        parentItem: "sandwich",
        sequence: 5,
        foodItemId: "bread_slices",
        colour: "blue",
      },
      { zone: "A", foodItemId: "fries", colour: "light green" },
    ],
  },
  {
    orderNo: "7420",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 7 4 2 0. I want a snack board at zone \"B\" with orange bacon, purple fries, yellow corn, and light green capsicum. Put pink flower candy at zone \"D\".",
    items: [
      {
        zone: "B",
        parentItem: "snack_board",
        sequence: 1,
        foodItemId: "bacon",
        colour: "orange",
      },
      {
        zone: "B",
        parentItem: "snack_board",
        sequence: 2,
        foodItemId: "fries",
        colour: "purple",
      },
      {
        zone: "B",
        parentItem: "snack_board",
        sequence: 3,
        foodItemId: "corn",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "snack_board",
        sequence: 4,
        foodItemId: "capsicum",
        colour: "light green",
      },
      { zone: "D", foodItemId: "flower_candy", colour: "pink" },
    ],
  },
  {
    orderNo: "4381",
    difficulty: "hard",
    customerSlot: 1,
    spokenText:
      "Order number 4 3 8 1. I want a noodle and bread combo. Zone \"A\" has red noodles with dark green mushroom. Zone \"C\" has brown small loaf. Zone \"D\" has yellow round candy.",
    items: [
      {
        zone: "A",
        parentItem: "noodle_combo",
        sequence: 1,
        foodItemId: "noodles",
        colour: "red",
      },
      {
        zone: "A",
        parentItem: "noodle_combo",
        sequence: 2,
        foodItemId: "mushroom",
        colour: "dark green",
      },
      { zone: "C", foodItemId: "small_loaf", colour: "brown" },
      { zone: "D", foodItemId: "round_candy", colour: "yellow" },
    ],
  },
  {
    orderNo: "8027",
    difficulty: "hard",
    customerSlot: 2,
    spokenText:
      "Order number 8 0 2 7. I want a burger at zone \"B\" with pink top burger bun, dark green cheese, orange tomato, red lettuce, purple bacon, and pink bottom burger bun. Put blue heart candy at zone \"A\".",
    items: [
      {
        zone: "B",
        parentItem: "burger",
        sequence: 1,
        foodItemId: "burger_bun",
        colour: "pink",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 2,
        foodItemId: "cheese",
        colour: "dark green",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 3,
        foodItemId: "tomato",
        colour: "orange",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "red",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 5,
        foodItemId: "bacon",
        colour: "purple",
      },
      {
        zone: "B",
        parentItem: "burger",
        sequence: 6,
        foodItemId: "burger_bun",
        colour: "pink",
      },
      { zone: "A", foodItemId: "heart_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "1759",
    difficulty: "hard",
    customerSlot: 3,
    spokenText:
      "Order number 1 7 5 9. I want a veggie feast at zone \"C\" with yellow cauliflower, red carrot, blue corn, light green capsicum, and orange mushroom. I also want purple round popsicle at zone \"B\".",
    items: [
      {
        zone: "C",
        parentItem: "veggie_feast",
        sequence: 1,
        foodItemId: "cauliflower",
        colour: "yellow",
      },
      {
        zone: "C",
        parentItem: "veggie_feast",
        sequence: 2,
        foodItemId: "carrot",
        colour: "red",
      },
      {
        zone: "C",
        parentItem: "veggie_feast",
        sequence: 3,
        foodItemId: "corn",
        colour: "blue",
      },
      {
        zone: "C",
        parentItem: "veggie_feast",
        sequence: 4,
        foodItemId: "capsicum",
        colour: "light green",
      },
      {
        zone: "C",
        parentItem: "veggie_feast",
        sequence: 5,
        foodItemId: "mushroom",
        colour: "orange",
      },
      { zone: "B", foodItemId: "round_popsicle", colour: "purple" },
    ],
  },
  {
    orderNo: "6209",
    difficulty: "hard",
    customerSlot: 4,
    spokenText:
      "Order number 6 2 0 9. I want a bread plate at zone \"D\" with dark green round bun, brown baguette, orange bread slices, and pink cinnamon roll. Put blue star candy at zone \"A\".",
    items: [
      {
        zone: "D",
        parentItem: "bread_plate",
        sequence: 1,
        foodItemId: "round_bun",
        colour: "dark green",
      },
      {
        zone: "D",
        parentItem: "bread_plate",
        sequence: 2,
        foodItemId: "baguette",
        colour: "brown",
      },
      {
        zone: "D",
        parentItem: "bread_plate",
        sequence: 3,
        foodItemId: "bread_slices",
        colour: "orange",
      },
      {
        zone: "D",
        parentItem: "bread_plate",
        sequence: 4,
        foodItemId: "cinnamon_roll",
        colour: "pink",
      },
      { zone: "A", foodItemId: "star_candy", colour: "blue" },
    ],
  },
  {
    orderNo: "3946",
    difficulty: "hard",
    customerSlot: 5,
    spokenText:
      "Order number 3 9 4 6. I want a hotdog combo at zone \"B\" with yellow hotdog, purple round bun, red tomato, and dark green lettuce. I also want orange fries at zone \"D\" and pink rectangular candy at zone \"A\".",
    items: [
      {
        zone: "B",
        parentItem: "hotdog_combo",
        sequence: 1,
        foodItemId: "hotdog",
        colour: "yellow",
      },
      {
        zone: "B",
        parentItem: "hotdog_combo",
        sequence: 2,
        foodItemId: "round_bun",
        colour: "purple",
      },
      {
        zone: "B",
        parentItem: "hotdog_combo",
        sequence: 3,
        foodItemId: "tomato",
        colour: "red",
      },
      {
        zone: "B",
        parentItem: "hotdog_combo",
        sequence: 4,
        foodItemId: "lettuce",
        colour: "dark green",
      },
      { zone: "D", foodItemId: "fries", colour: "orange" },
      { zone: "A", foodItemId: "rectangular_candy", colour: "pink" },
    ],
  },
  {
    orderNo: "9572",
    difficulty: "hard",
    customerSlot: 6,
    spokenText:
      "Order number 9 5 7 2. I want a final mix. Zone \"A\" has blue dumpling. Zone \"B\" has brown bacon and yellow corn. Zone \"C\" has dark green cheese. Zone \"D\" has purple flower candy.",
    items: [
      { zone: "A", foodItemId: "dumpling", colour: "blue" },
      {
        zone: "B",
        parentItem: "final_mix",
        sequence: 1,
        foodItemId: "bacon",
        colour: "brown",
      },
      {
        zone: "B",
        parentItem: "final_mix",
        sequence: 2,
        foodItemId: "corn",
        colour: "yellow",
      },
      { zone: "C", foodItemId: "cheese", colour: "dark green" },
      { zone: "D", foodItemId: "flower_candy", colour: "purple" },
    ],
  },
];
